Added 8.1
valeria-ivasheva/homework pull request #9
Opened 2017-12-23 13:55 UTC by valeria-ivasheva

splay-дерево
Исправлены баги

2017-12-23 20:52 UTC, yurii-litvinov requested changes
Я, кстати, нашёл, как сделать так, чтобы консоль не закрывалась сразу же при запуске через Ctrl-F5. Это в свойствах проекта (правый клик по файлу с проектом), Configuration Properties -> Linker -> System, надо поставить SubSystem Console.

2017-12-23 20:52 UTC, yurii-litvinov commented on homework 8/splay/splay/Node.h
> +//void printTree(Tree* tree);
Закомментированный код в основной ветке не нужен, это некоторая неаккуратность

2017-12-23 20:52 UTC, yurii-litvinov commented on homework 8/splay/splay/Node.h
> +using std::string;
Тоже нехорошо. Лучше std:: перед всеми string в .h-нике писать

2017-12-23 20:52 UTC, yurii-litvinov commented on homework 8/splay/splay/Node.h
> +bool isHaveKey(Tree* tree, const string &key);
hasKey правильнее

2017-12-23 20:52 UTC, yurii-litvinov commented on homework 8/splay/splay/Node.cpp
> +	}
Мне кажется, что мы так забываем сказать node, что у него родитель поменялся, поэтому zig будет работать странно. И вообще, мне кажется, что этого можно не делать, zig сам разберётся с родителем, разве нет?

2017-12-23 20:52 UTC, yurii-litvinov commented on homework 8/splay/splay/Node.cpp
> +	return;
Лишний return

2017-12-23 20:52 UTC, yurii-litvinov commented on homework 8/splay/splay/Node.cpp
> +	bool isZigzig = (grandparent->leftChild == parent && parent->leftChild == node) || (grandparent->rightChild == parent && parent->rightChild == node);
Слишком уж длинная строчка, лучше
```c++
bool isZigzig = (grandparent->leftChild == parent && parent->leftChild == node) 
        || (grandparent->rightChild == parent && parent->rightChild == node);
```

2017-12-23 20:52 UTC, yurii-litvinov commented on homework 8/splay/splay/Node.cpp
> +			node->parent->rightChild == nullptr;
Я думаю, с "==" тут опечатка

2017-12-24 10:10 UTC, valeria-ivasheva commented on homework 8/splay/splay/Node.cpp
> +	}
Теперь он сам разберется.
Но раньше он не перевешивал node, как сына для grandparent, я немного исправила zig

2017-12-27 11:08 UTC, yurii-litvinov approved these changes
Вроде всё ок, зачтена

2018-02-15 13:01 UTC, merged